apps/plantillas/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',		

	
	url(r'^home-item/$', 'apps.plantillas.views.HomeItem' , name='Item'),
	url(r'^create-item/$', 'apps.plantillas.views.CreateItem' , name='createitem'),
	url(r'^buscar-item/$', 'apps.plantillas.views.BuscarItem' , name='buscaritem'),
	url(r'^modi-item/$', 'apps.plantillas.views.ModiItem' , name='modificaritem '),
	url(r'^plantilla-consulta/$', 'apps.plantillas.views.PlantConsulta' , name='PlantillaConsulta'),
	url(r'^reporte/resultado/(?P<idpaciente>[^/]+)/(?P<iddetalle>[^/]+)/$', 'apps.plantillas.views.crear_reporte_resultado', name='ReporteHorarioServicio'),

)

proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.inicio.urls')),
    url(r'^', include('apps.logistica.urls')),
    url(r'^', include('apps.rr_hh.urls')),
    url(r'^', include('apps.solicitudes.urls')),
    url(r'^', include('apps.plantillas.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
       {'document_root': settings.MEDIA_ROOT, } ),
    )

apps/plantillas/models.py
from django.db import models
from apps.logistica.models import Servicio
# Create your models here.

class Item(models.Model):
    item_nombre = models.CharField(max_length=70)
    item_descripcion = models.TextField(blank=True)
    item_valor_referencial = models.CharField(max_length=100)
    item_estado = models.BooleanField(default=True)
    servi = models.ForeignKey(Servicio)
    def __unicode__(self):
        return self.item_nombre

apps/plantillas/forms.py
from django import forms
from .models import Item


class RegistrarItemForm(forms.ModelForm):
	id = forms.IntegerField(required=False,widget = forms.HiddenInput(
		attrs={ 'id': 'codigo'}))
	item_nombre = forms.CharField(widget= forms.TextInput(
		attrs={ 'class' : 'input-sm', 'id': 'nombres'}))	
	item_valor_referencial = forms.CharField(required=False,widget= forms.TextInput(
		attrs={ 'class' : 'input-sm', 'id': 'valor'}))	
	item_descripcion = forms.CharField(required=False,widget= forms.Textarea(
		attrs={'class' : 'custom-scroll' , 'id': 'observacion'}))	
	class Meta:
		model = Item

apps/plantillas/views.py
from django.shortcuts import render, redirect, render_to_response
from django.views.generic import TemplateView
from apps.solicitudes.models import Resultado, Solicitud, Paciente
from apps.rr_hh.models import Programacion
from .forms import RegistrarItemForm
from django.shortcuts import render_to_response
from django.core import serializers
from django.http import HttpResponse, Http404, HttpResponseRedirect
import json


from django.template import RequestContext
import os
import StringIO
from xhtml2pdf import pisa
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404


def crear_reporte_resultado(request,idpaciente,iddetalle):
	consulta = Resultado.objects.filter(detallesoli=iddetalle)
	paciente = get_object_or_404(Paciente, id=idpaciente)
	print paciente
	lista=[]
	for carga in consulta:	
		programacion = get_object_or_404(Programacion, id=carga.detallesoli.programacion.id)				
		d={'valor':carga.resul_valor1,'pk':carga.item.id,'item':carga.item.item_nombre,'fecha':carga.detallesoli.programacion.hor_fecha}
		lista.append(d)
	html = render_to_string("plantillas/reporteplantilla.html",{'pagesize':'A4','lista':lista,'programacion':programacion,'paciente':paciente}, context_instance=RequestContext(request))
	return generar_pdf_servicio(html)


def generar_pdf_servicio(html):
	 resultado=StringIO.StringIO()
	 pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), resultado)
	 if not pdf.err:
	     return HttpResponse(resultado.getvalue(), mimetype='application/pdf')
	 return HttpResponse('Error al generar el PDF')

def CreateItem(request):	
	if request.method == 'POST':
		form = RegistrarItemForm(request.POST)
		response_data = {} 
		if form.is_valid():
			item= Item()
			item.item_nombre = form.cleaned_data.get('item_nombre')	
			item.servi = form.cleaned_data.get('servi')	
			item.item_valor_referencial = form.cleaned_data.get('item_valor_referencial')	
			item.item_descripcion = form.cleaned_data.get('item_descripcion')			
			item.save()		
			response_data['result'] = "El nuevo item fue Registrado con Exito"
			#response_data['postpk'] = paciente.pk	        print "XXSS"
			#paciente.pac_fecnac = form.cleaned_data.get('DNI')	        
			return HttpResponse(json.dumps(response_data),content_type="application/json")
		else:
			data = json.dumps({'errors': dict([(k, [unicode(e) for e in v]) for k,v in form.errors.items()])})        
			return HttpResponse(data,content_type="application/json")
	else:
		return HttpResponse(json.dumps({"nothing to see": "this isn't happening"}),content_type="application/json")	

def BuscarItem(request):		
	if request.is_ajax():			
		texto= request.GET['texto']
		seleccion = request.GET['seleccion']
		if seleccion=="0":
			consulta = Item.objects.select_related().filter(item_nombre__icontains=texto)
			lista=[]
			for item in consulta:
				d={'pk':item.id,'item': item.item_nombre,'valor': item.item_valor_referencial,'descripcion': item.item_descripcion
				,'fk':item.servi.id,'Servicio':item.servi.servi_nom}
				lista.append(d)	
			return HttpResponse(json.dumps(lista), content_type='application/json')	

		elif seleccion=="1":
			consulta = Item.objects.select_related().filter(servi__servi_nom__icontains=texto)
			lista=[]
			for item in consulta:
				d={'pk':item.id,'item': item.item_nombre,'valor': item.item_valor_referencial,'descripcion': item.item_descripcion
				,'fk':item.servi.id,'Servicio':item.servi.servi_nom}
				lista.append(d)	
			return HttpResponse(json.dumps(lista), content_type='application/json')
		elif seleccion=="2":
			consulta = Item.objects.select_related().filter(servi__id__icontains=texto)
			lista=[]
			for item in consulta:
				d={'pk':item.id,'item': item.item_nombre,'valor': item.item_valor_referencial,'descripcion': item.item_descripcion
				,'fk':item.servi.id,'Servicio':item.servi.servi_nom}
				lista.append(d)	
			return HttpResponse(json.dumps(lista), content_type='application/json')	
	else :
		print "mal"
		raise Http404

def ModiItem(request):	
	if request.method == 'POST':
		form = RegistrarItemForm(request.POST)
		response_data = {} 
		if form.is_valid():
			item= Item.objects.get(id=form.cleaned_data.get('id'))	
			item.item_nombre = form.cleaned_data.get('item_nombre')	
			item.servi = form.cleaned_data.get('servi')	
			item.item_valor_referencial = form.cleaned_data.get('item_valor_referencial')	
			item.item_descripcion = form.cleaned_data.get('item_descripcion')			
			item.save()		
			response_data['result'] = "Los datos de la Categoria fueron Actualizados con Exito"  
			return HttpResponse(json.dumps(response_data),content_type="application/json")

		else:
			data = json.dumps({'errors': dict([(k, [unicode(e) for e in v]) for k,v in form.errors.items()])})        
			return HttpResponse(data,content_type="application/json")
	else:
		return HttpResponse(json.dumps({"nothing to see": "this isn't happening"}),content_type="application/json")	

def HomeItem(req):
	tmpl_vars = {
		'form': RegistrarItemForm()
	}
	return render(req, 'plantillas/plantillaitem.html', tmpl_vars)


def PlantConsulta(req):
	return render(req, 'plantillas/treeview.html')

templates/plantillas/plantillaitem.html
<body>
<div class="row">
	<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h1 class="page-title txt-color-blueDark">
			<i class="fa fa-pencil-square-o fa-fw "></i> 
				Items
			<span>> 
				Administracion de Items
			</span>
		</h1>
	</div>	
</div>
<section id="widget-grid" class="">
	<div class="row">
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">				
				<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2>Lista de Items</h2>
				</header>
				<div>
					<div class="jarviswidget-editbox">
					</div>
					<div class="widget-body no-padding">
						<div class="table-responsive">
							
							<table class="table">
							<thead>			                
								<tr>
									<th >ID</th>
									<th data-class="expand"><i class="fa fa-fw fa-user text-muted hidden-md hidden-sm hidden-xs"></i> Item</th>
									<th data-hide="phone,tablet"><i></i> Valor Referencial</th>
									<th data-hide="phone,tablet"><i></i> Descripcion</th>
									<th data-hide="phone,tablet"><i></i> Servicio</th>
									<th data-class="expand"></th>
									 </tr> </thead> <tbody id = "Tematico">
							</tbody>
						</table>
						</div>

					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
		</article>
	</div>

	
	<div class="row">


		<!-- NEW COL START -->
		<article class="col-sm-12 col-md-12 col-lg-6">
		<div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false">
				
				<header>
					<span class="widget-icon"> <i class="fa fa-eye-slash"></i> </span>
					<h2>Realizar Busqueda</h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<div class="widget-body">

						<form class="form-horizontal">
							
							<fieldset>
								<div class="form-group">
									<label class="col-md-2 control-label" for="select-1">Seleccione </label>
									<div class="col-md-10">
										<select class="form-control" id="selitem">
											<option value="0">Nombre del Item</option>
											<option value="1">Nombre de la Servicio</option>	
										</select> 
									</div>
								</div>							
								<div class="well">		
								<div class="input-group">
									<input class="form-control" type="text" placeholder="Buscar..." id="texto">
										<div class="input-group-btn">
											<button class="btn btn-default btn-primary" type="button" id="buscar">
											<i class="fa fa-search"></i> Buscar
											</button>
										</div>
								</div>
								</div>
								
							</fieldset>
						</form>

					</div>
				</div>				
			</div>

		</article>
		<article class="col-sm-12 col-md-12 col-lg-6">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget" id="wid-id-2" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
					<h2>Registro de Item Nuevos </h2>

				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">

						<form method="POST" class="smart-form" id = "post-form">
							<header>
								Registro de Item
							</header>
							
							<fieldset>	
							{% csrf_token %}							
								<section>
									<label class="label"  >{{form.id}}</label>
									<label class="label">Nombre:</label>
									<label class="input" id="lblnombitem">
										{{form.item_nombre}}
									</label>
									<div class="note note-error" id="eNon"></div>
								</section>	
								<section>
									<label class="label">Seleccione el Servicio</label>
									<label class="select" id="lblitemcate">
										{{form.servi}}
									</label>
									<div class="note note-error" id="eItem"></div>
								</section>					
								<section>
									<label class="label">Valor Referencial:</label>
									<label class="input"id="lblvalitem"> {{form.item_valor_referencial}}				
									</label>						
								</section>
								<section>
									<label class="label">Observaciones</label>
									<label class="textarea textarea-expandable"> {{form.item_descripcion}}				
									</label>						
								</section>									
							</fieldset>		
							<div id="results"></div>							
							<footer>
								<button type="button" class="btn btn-success disabled" type="button" id="btncambios"><i class="fa fa-save" ></i>
									Guardar Cambios
								</button>
								<button type="submit"  class="btn btn-primary" id="btnGuardar">
									Guardar
								</button>
								<button type="button" class="btn btn-default" onclick="window.history.back();">
									Regresar
								</button>
							</footer>
						</form>

					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->

		</article>
	</div>


</section>

<script >
$(document).off( "click", ".btn-danger" )
$(document).off( "click", ".bg-color-magenta")
$(document).off( "click", ".bg-color-red")
$(document).off( "click", ".bg-color-blue")

$('#post-form').on('submit', function(event){
    event.preventDefault();     
    create_post();});
    function create_post() { 
    $.ajax({
        url: '/create-item/',
        type : "POST",
        data : $('#post-form').serialize(), 
        success : function(json) 
        {        	
            if (json.errors)
            {
            	if(json.errors.item_nombre)
            	{            		
            		$('#lblnombitem').removeClass('input state-success');
            		$('#lblnombitem').addClass('input state-error')
            		$("#eNon").text(json.errors.item_nombre);
            	}else
            	{
            		$('#lblnombitem').addClass('input state-success');
            		$("#eNon").text( "");
                }
                if(json.errors.servi)
            	{            		
            		$('#lblitemcate').removeClass('input state-success');
            		$('#lblitemcate').addClass('input state-error')
            		$("#eItem").text(json.errors.servi);
            	}else
            	{
            		$('#lblitemcate').addClass('input state-success');
            		$("#eItem").text("");
                }
            }
            else
            {
            	alert(json.result);
            	location.reload();
            }
        }
    });
};

$("#btncambios").on("click", guarCambios)
	function guarCambios()
	{
		$.ajax({
        url: '/modi-item/',
        type : "POST",
        data : $('#post-form').serialize(), 
        success : function(json) 
        {
        	if (json.errors)
            {
            	if(json.errors.item_nombre)
            	{            		
            		$('#lblnombitem').removeClass('input state-success');
            		$('#lblnombitem').addClass('input state-error')
            		$("#eNon").text(json.errors.item_nombre);
            	}else
            	{
            		$('#lblnombitem').addClass('input state-success');
            		$("#eNon").text( "");
                }
                if(json.errors.cate)
            	{            		
            		$('#lblitemcate').removeClass('input state-success');
            		$('#lblitemcate').addClass('input state-error')
            		$("#eItem").text(json.errors.cate);
            	}else
            	{
            		$('#lblitemcate').addClass('input state-success');
            		$("#eItem").text("");
                }
            }
            else
            {
            	alert(json.result);
            	location.reload();
            }
				//console.log(json)
		}
		});
	}




function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
 function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
        // or any other URL that isn't scheme relative or absolute i.e relative.
        !(/^(\/\/|http:|https:).*/.test(url));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
            // Send the token to same-origin, relative URLs only.
            // Send the token only if the method warrants CSRF protection
            // Using the CSRFToken value acquired earlier
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
	$("#buscar").on("click", metodo)
	function metodo()
	{
		$('#btncambios').addClass('disabled')
		$('#btnGuardar').removeClass('disabled')
		var opcion=$(texto).val()
		var seleccion = $(selitem).val()
		$.ajax({ 
			data: {'texto': opcion,'seleccion': seleccion},
			url: '/buscar-item/',
			type: 'get',
			success: function(data)
			{
				$("#Tematico tr").remove();
				for (var i=0; i<data.length; i++)
				{									
					var tr = '<tr>';
					var td1 = '<td>' + data[i].pk + '</td>';
               var td2 = '<td>' + data[i].item +'</td>';
               var td3 = '<td>' + data[i].valor +'</td>';
               var td4 = '<td>' + data[i].descripcion +'</td>';
               var td5 = '<td>' + data[i].Servicio +'</td>';
               var td6 = '<td style="display:none;">' + data[i].fk + "</td>";
               var td8 = '<td><a href="javascript:void(0);" class="btn bg-color-magenta txt-color-white btn-circle" id="'+ data[i].pk + '" data-name="'+data[i].pk+'"><i class="fa fa-pencil"></i></a></td></tr>'
               

               $("#Tematico").append(tr+td1+td2+td3+td4+td5+td6+td8);					
					//alert("dddd");
				}
			}
		});
	}

	$(document).on("click",".bg-color-magenta",cargamodi);
	function cargamodi()
	{
		fila = $(this).closest('tr').index();
		$('#btncambios').removeClass('disabled')
		$("#codigo").val($('#Tematico tr:eq('+fila+') td:eq('+0+')').text())
		$('#btnGuardar').addClass('disabled')   	
		$("#nombres").val($('#Tematico tr:eq('+fila+') td:eq('+1+')').text())
		$("#valor").val($('#Tematico tr:eq('+fila+') td:eq('+2+')').text())
		$("#observacion").val($('#Tematico tr:eq('+fila+') td:eq('+3+')').text())
		$("#id_servi").val($('#Tematico tr:eq('+fila+') td:eq('+5+')').text())

	}


	</script>

<script type="text/javascript">

	/* DO NOT REMOVE : GLOBAL FUNCTIONS!
	 *
	 * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
	 *
	 * // activate tooltips
	 * $("[rel=tooltip]").tooltip();
	 *
	 * // activate popovers
	 * $("[rel=popover]").popover();
	 *
	 * // activate popovers with hover states
	 * $("[rel=popover-hover]").popover({ trigger: "hover" });
	 *
	 * // activate inline charts
	 * runAllCharts();
	 *
	 * // setup widgets
	 * setup_widgets_desktop();
	 *
	 * // run form elements
	 * runAllForms();
	 *
	 ********************************
	 *
	 * pageSetUp() is needed whenever you load a page.
	 * It initializes and checks for all basic elements of the page
	 * and makes rendering easier.
	 *
	 */

	pageSetUp();
	
	/*
	 * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
	 * eg alert("my home function");
	 * 
	 * var pagefunction = function() {
	 *   ...
	 * }
	 * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
	 * 
	 * TO LOAD A SCRIPT:
	 * var pagefunction = function (){ 
	 *  loadScript(".../plugin.js", run_after_loaded);	
	 * }
	 * 
	 * OR
	 * 
	 * loadScript(".../plugin.js", run_after_loaded);
	 */

	// PAGE RELATED SCRIPTS

	// pagefunction
	
	var pagefunction = function() {
		
		// class switcher for radio and checkbox
		$('input[name="demo-switcher-1"]').change( function() {
		  //alert($(this).val())
		  $this = $(this);
		  
		  myNewClass = $this.attr('id');
		  
		  $('.demo-switcher-1 input[type="checkbox"]').removeClass();
		  $('.demo-switcher-1 input[type="checkbox"]').addClass("checkbox "+ myNewClass);
		  
		  $('.demo-switcher-1 input[type="radio"]').removeClass();
		  $('.demo-switcher-1 input[type="radio"]').addClass("radiobox "+ myNewClass);
		  
		});
		
	};
	
	// end pagefunction
	
	// run pagefunction on load
	
	pagefunction();
	
</script>

templates/plantillas/reporteplantilla.html
{% extends "base.html" %}
{% block contenido %}
<style type="text/css">
	h1{color: #000000; text-align: center; text-decoration:underline;}
	.cabe{font-weight: bold; background: #1E90FF; color: white;}
</style>
</div>
<table border="0">
<th width="70%"><img src='static/images/titulo4.jpg'/></br><strong style="font-style:italic; font-size:13px;">&nbsp;&nbsp; Jr. Progreso 331 - Barranca  Telefono: 2352565 Celular: 998170923</strong></th>
<th width="30%"><img align="right" src='static/images/logo3.jpg'/></th>
</table>
<hr>
<div>
	<h1>INFORME DE RESULTADOS MEDICOS</h1>
</div>
<table border="0" style="padding: 8px 1px 1px 1px; background: #E6E6FA">
<th width="10%" align="center" style="font-size:11px; font-family:Georgia;"><strong style="color: #000000;">PACIENTE:</strong></th>
<th width="40%" align="left" style="font-size:11px; font-family:Georgia;"><strong style="color: #000000;">&nbsp;{{paciente.pac_nombre}}&nbsp;{{paciente.pac_apellido}}</strong></th>

<th width="15%" align="center" style="font-size:11px; font-family:Georgia;"><strong style="color: #000000;">FECHA DE CITA:</strong> <strong style="color: #FF1493;"></th>
<th width="35%" align="left" style="font-size:11px; font-family:Georgia;"><strong style="color: #000000;">&nbsp;{{programacion.hor_fecha}}</strong> <strong style="color: #FF1493;"></strong></th>
</table>

</br>
<section>
<div>
<table id="tabla" border="0px" width="100%" align="center" height="10px" style="padding:3px" style="background: #eee;">
{% for i in lista %}
<tr>
<td width="20%" align="left" style="font-size:14px; font-family:Georgia;"><strong style="color: #000000;">{{ i.item}}</strong></td>
<td width="80%" align="left" style="font-size:14px; font-family:Georgia;"><strong style="color: #000000;"><i>&nbsp;{{ i.valor}}</i></strong></td>
</tr>
{% endfor %}

				

</table>
</div>
</section>
{% endblock %}